/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class SignUpFrame extends javax.swing.JFrame {
    ImageIcon imgIcon;
    CustomFont customFont;
    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        Image AppIcon = new ImageIcon(this.getClass().getResource("/Logo_Icon.png")).getImage();
        this.setIconImage(AppIcon);
        initComponents();
        showTextFeild();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtCfPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnBack_default.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 60, 70));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 270, 50));

        txtCfPassword.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtCfPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtCfPassword.setBorder(null);
        getContentPane().add(txtCfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 270, 50));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 280, 50));

        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnSignUp_default.png"))); // NOI18N
        btnSignUp.setBorder(null);
        btnSignUp.setBorderPainted(false);
        btnSignUp.setContentAreaFilled(false);
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 200, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpFrame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        try{
            String filePath = "/btnBack_hover.png";
            imgIcon = new ImageIcon(getClass().getResource(filePath));
            btnBack.setIcon(imgIcon);
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        try{
            String filePath = "/btnBack_default.png";
            imgIcon = new ImageIcon(getClass().getResource(filePath));
            btnBack.setIcon(imgIcon);
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        UserOptionFrame userOptionFrame = new UserOptionFrame();
        userOptionFrame.setVisible(true);
        userOptionFrame.pack();
        userOptionFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        try{
            String filePath = "/btnSignUp_hover.png";
            imgIcon = new ImageIcon(getClass().getResource(filePath));
            btnSignUp.setIcon(imgIcon);
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        try{
            String filePath = "/btnSignUp_default.png";
            imgIcon = new ImageIcon(getClass().getResource(filePath));
            btnSignUp.setIcon(imgIcon);
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String username,password, cfPassword;
        //Check Feild is null?
        if("".equals(txtUsername.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }else if("".equals(txtPassword.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }else if("".equals(txtCfPassword.getText())){
            JOptionPane.showMessageDialog(new JFrame(), "Confirm Password is required", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        }else{
            username = txtUsername.getText();
            password = txtPassword.getText();  
            cfPassword = txtCfPassword.getText(); 
            if(cfPassword.equals(password)){
                insertToDB(username,password);
                txtUsername.setText("");
                txtPassword.setText("");
                txtCfPassword.setText("");
                JOptionPane.showMessageDialog(null, "Sign Up Successful");
                
                // After show pop-up message back into LoginPage
                LoginFrame loginFrame = new LoginFrame();
                loginFrame.setVisible(true);
                loginFrame.pack();
                loginFrame.setLocationRelativeTo(null);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Confirm password is not match.","Warning",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSignUpActionPerformed
    
    private void showTextFeild(){
        txtUsername.setBackground(new java.awt.Color(0,0,0,0));
        txtUsername.setOpaque(false);
        txtUsername.repaint();
        
        txtPassword.setBackground(new java.awt.Color(0,0,0,0));
        txtPassword.setOpaque(false);
        txtPassword.repaint();
        
        txtCfPassword.setBackground(new java.awt.Color(0,0,0,0));
        txtCfPassword.setOpaque(false);
        txtCfPassword.repaint();
        
        customFont = new CustomFont();
        Font font = customFont.setFontFile(22);
        txtUsername.setFont(font);
    }
    
    private static void insertToDB(String username, String password){
        try{
            Connection con = DbConnection.connect();
            PreparedStatement cursor = null;
            try{
                String sqlInsert = "INSERT INTO userAccount(username,password) VALUES(?,?)";
                cursor = con.prepareStatement(sqlInsert);
                cursor.setString(1, username);
                cursor.setString(2, password);
                cursor.execute();
                System.out.println("Data has been inserted!");
            }catch(SQLException e){
                System.out.println(e.toString());
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtCfPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
